### ISSUE TITLE
BUG: PHP 7.4 not working anymore

### ISSUE THREAD

**Issue by paavo** [flownative/flow-sentry#21]
https://github.com/flownative/flow-sentry/commit/19fe95425c077594f51092c6336dbcd86aa923bc#commitcomment-104519930
@kdambekalns

**Comment by paavo** [comment]
Oh, i run into this issue again 🙈 
Any plans to fix this @kdambekalns?

**Comment by kdambekalns** [comment]
As #23 shows, the fix was there for ages. No clue why I never created a PR… 🙈

**Comment by kdambekalns** [comment]
Fixed with https://github.com/flownative/flow-sentry/releases/tag/v1.3.2
